stages:
  - docker-swarm-deploy-rabbitmq
  - docker-swarm-deploy-zipkin
#  - docker-swarm-deploy-sentry

docker-swarm-deploy-rabbitmq:
  stage: docker-swarm-deploy-rabbitmq
  script:
    - touch .env_rabbit
    - echo "RABBITMQ_DEFAULT_USER='admin'" >> .env_rabbit
    - echo "RABBITMQ_DEFAULT_PASS=$RABBIT_PASS" >> .env_rabbit
    - sudo docker stack deploy -c deploy-rabbitmq.yaml socshared

docker-swarm-deploy-zipkin:
  stage: docker-swarm-deploy-zipkin
  script:
    - touch .env_zipkin
    - echo "RABBIT_URI=amqp://admin:$RABBIT_PASS@rabbitmq:5672" >> .env_zipkin
    - sudo docker stack deploy -c deploy-zipkin.yaml socshared

#docker-swarm-deploy-postgres:
#  stage: docker-swarm-deploy-postgres
#  script:
#    - sudo docker stack deploy -c deploy-postgres.yaml socshared
#
#docker-swarm-deploy-sentry:
#  stage: docker-swarm-deploy-sentry
#  script:
#    - sudo docker stack deploy -c deploy-sentry.yaml socshared