stages:
  - docker-swarm-deploy-rabbitmq
  - docker-swarm-deploy-zipkin
#  - docker-swarm-deploy-sentry

docker-swarm-deploy-rabbitmq:
  stage: docker-swarm-deploy-rabbitmq
  script:
    - sudo docker stack deploy -c deploy-rabbitmq.yaml socshared

docker-swarm-deploy-zipkin:
  stage: docker-swarm-deploy-zipkin
  script:
    - sudo docker stack deploy -c deploy-zipkin.yaml socshared

#docker-swarm-deploy-postgres:
#  stage: docker-swarm-deploy-postgres
#  script:
#    - sudo docker stack deploy -c deploy-postgres.yaml socshared
#
#docker-swarm-deploy-sentry:
#  stage: docker-swarm-deploy-sentry
#  script:
#    - sudo docker stack deploy -c deploy-sentry.yaml socshared