stages:
  - docker-swarm-deploy-redis-postgres
  - docker-swarm-deploy-zipkin
  - docker-swarm-deploy-sentry
  - docker-swarm-deploy-rabbitmq

docker-swarm-deploy-redis-postgres:
  stage: docker-swarm-deploy-redis-postgres
  script:
    - sudo docker stack deploy -c deploy-redis-postgres.yaml socshared

docker-swarm-deploy-zipkin:
  stage: docker-swarm-deploy-zipkin
  script:
    - sudo docker stack deploy -c deploy-zipkin.yaml socshared

docker-swarm-deploy-sentry:
  stage: docker-swarm-deploy-sentry
  script:
    - touch .env
    - echo "SENTRY_SECRET_KEY=$SENTRY_KEY" >> .env
    - echo "SENTRY_POSTGRES_HOST=socshared_sentry_postgres" >> .env
    - echo "SENTRY_DB_USER=sentry" >> .env
    - echo "SENTRY_DB_PASSWORD=171322f63734464e9e58deb6e9a419e5" >> .env
    - echo "SENTRY_REDIS_HOST=socshared_sentry_redis" >> .env
    - sudo docker stack deploy -c deploy-sentry.yaml socshared
#     автоматическая настройка Sentry в данный момент невозможна
#     sudo docker exec $CONTAINER_ID "sentry upgrade && sentry createuser --email vladovchinnikov950@gmail.com --password admin --superuser --no-input"

docker-swarm-deploy-rabbitmq:
  stage: docker-swarm-deploy-rabbitmq
  script:
    - sudo docker stack deploy -c deploy-rabbitmq.yaml socshared