stages:
  - docker-swarm-deploy-postgres-redis
  - docker-swarm-deploy-zipkin
  - docker-swarm-deploy-sentry

docker-swarm-deploy-postgres-redis:
  stage: docker-swarm-deploy-postgres-redis
  script:
    - sudo docker network create -d overlay socshared
    - sudo docker stack deploy -c deploy-postgres-redis.yaml socshared

docker-swarm-deploy-zipkin:
  stage: docker-swarm-deploy-zipkin
  script:
    - sudo docker stack deploy -c deploy-zipkin.yaml socshared

docker-swarm-deploy-sentry:
  stage: docker-swarm-deploy-sentry
  script:
    - sudo docker stack deploy -c deploy-sentry.yaml socshared