stages:
  - docker-swarm-deploy-zipkin
  - docker-swarm-deploy-sentry
  - docker-swarm-deploy-rabbitmq

docker-swarm-deploy-zipkin:
  stage: docker-swarm-deploy-zipkin
  script:
    - sudo docker stack deploy -c deploy-zipkin.yaml socshared

docker-swarm-deploy-sentry:
  stage: docker-swarm-deploy-sentry
  script:
    - touch .env
    - echo "SENTRY_SECRET_KEY=$SENTRY_KEY\n" >> .env
    - echo "SENTRY_POSTGRES_HOST=sentry_postgres\n" >> .env
    - echo "SENTRY_DB_USER=sentry_postgres\n" >> .env
    - echo "SENTRY_DB_PASSWORD=171322f6-3734-464e-9e58-deb6e9a419e5\n" >> .env
    - echo "SENTRY_REDIS_HOST=sentry_redis\n" >> .env
    - sudo docker stack deploy -c deploy-sentry.yaml socshared
#    - sudo docker exec $(sudo docker ps -q -f name=socshared_sentry) sentry upgrade
#    - sudo docker exec $(sudo docker ps -q -f name=socshared_sentry) sentry createuser --email $VEE_EMAIL --password $VEE_PASSWORD --superuser --no-input

docker-swarm-deploy-rabbitmq:
  stage: docker-swarm-deploy-rabbitmq
  script:
    - sudo docker stack deploy -c deploy-rabbitmq.yaml socshared