version: '3.7'
services:
  auth_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    env_file:
      - .env_session_pg

  vk_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5433:5432
    env_file:
      - .env_vk_pg

  fb_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5434:5432
    env_file:
      - .env_fb_pg

  bstat_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5435:5432
    env_file:
      - .env_bstat_pg

  storage_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5436:5432
    env_file:
      - .env_storage_pg

networks:
  default:
    name: socshared