version: '3.7'
services:
  auth_postgres_db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - 5432:5432
    environment:
      - .env_session_pg

networks:
  default:
    name: socshared