version: '3.7'

volumes:
   pgdb:

services:
  sentry_redis:
    image: redis
    deploy:
      replicas: 1

#  sentry_postgres:
#    image: postgres
#    deploy:
#      replicas: 1
#    environment:
#      POSTGRES_USER: sentry
#      POSTGRES_PASSWORD: sentry
#      POSTGRES_DB: sentry
#    volumes:
#     - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    ports:
     - 9898:9898
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

  sentry_cron:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

  sentry_worker:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    command: "sentry run worker"
    deploy:
      replicas: 1
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY}"
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

networks:
  default:
    name: socshared
    driver: overlay
