version: '3.7'
services:

  zipkin:
    image: openzipkin/zipkin:2
    deploy:
      replicas: 1
    ports:
      - 9411:9411
    environment:
      - "RABBIT_URI=amqp://admin:/run/secrets/rabbitmq_external_secret@rabbitmq:5672"
    secrets:
      - rabbitmq_external_secret

secrets:
  rabbitmq_external_secret:
    external: true

networks:
  default:
    name: socshared