version: '3.7'

services:
  sentry:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: 'iwd+#q*0_(8xgtq&r2sl)ci(ive@7mc4)g9&d5)gr_8_(5(gdh'
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

  sentry_cron:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: 'iwd+#q*0_(8xgtq&r2sl)ci(ive@7mc4)g9&d5)gr_8_(5(gdh'
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

  sentry_worker:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    command: "sentry run worker"
    deploy:
      replicas: 1
    environment:
      SENTRY_SECRET_KEY: 'iwd+#q*0_(8xgtq&r2sl)ci(ive@7mc4)g9&d5)gr_8_(5(gdh'
      SENTRY_POSTGRES_HOST: sentry_postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: sentry_redis

networks:
  default:
    external:
      name: socshared
