version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin:2
    deploy:
      replicas: 1
    ports:
      - 9411:9411
    environment:
      RABBIT_LOGIN: 'admin'
      RABBIT_PASSWORD: /run/secrets/rabbit_file_secret
      RABBIT_URI: amqp://$RABBIT_LOGIN:$RABBIT_PASSWORD@socshared_rabbitmq:15672

secrets:
  rabbit_external_secret:
    external: true
  rabbit_file_secret:
    file: rabbitmq_file_secret.txt

networks:
  default:
    name: socshared