version: '3.7'

volumes:
  pgdb:

services:
  sentry_redis:
    image: redis
    deploy:
      replicas: 1

  sentry_postgres:
    image: postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - pgdb:/var/lib/postgresql/data

networks:
  default:
    external:
      name: socshared
