version: '3.7'

volumes:
  sentryv:

services:
  sentry:
    image: sentry
    deploy:
      replicas: 1
    ports:
     - 9000:9000
    env_file:
      - .env
    volumes:
      - sentryv:/var/lib/sentry/data

  sentry_cron:
    image: sentry
    deploy:
      replicas: 1
    command: "sentry run cron"
    env_file:
      - .env

  sentry_worker:
    image: sentry
    command: "sentry run worker"
    deploy:
      replicas: 1
    env_file:
      - .env

networks:
  default:
    name: socshared
