version: '3.7'

services:
  rabbitmq:
    image: 'rabbitmq:3.7.6-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_external_secret
      secrets:
        - rabbitmq_external_secret

secrets:
  rabbitmq_external_secret:
    external: true

networks:
  default:
    name: socshared