version: '3.7'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULE_PASS: 'guest'
#     RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_external_secret
#    secrets:
#      - rabbitmq_external_secret
#
#secrets:
#  rabbitmq_external_secret:
#    external: true

networks:
  default:
    name: socshared