version: '3.7'

services:
  sentry_redis:
    image: redis
    deploy:
      replicas: 1

  sentry_postgres:
    image: postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: 171322f63734464e9e58deb6e9a419e5
      POSTGRES_DB: sentry

networks:
  default:
    name: socshared