version: '3.7'

services:
  sentry:
    image: vee97/socshared_sentry
    deploy:
      replicas: 1
    ports:
     - 9000:9000
    env_file:
      - .env

  sentry_cron:
    image: vee97/socshared_sentry_cron
    deploy:
      replicas: 1
    command: "sentry run cron"
    env_file:
      - .env

  sentry_worker:
    image: vee97/socshared_sentry_worker
    command: "sentry run worker"
    deploy:
      replicas: 1
    env_file:
      - .env

networks:
  default:
    name: socshared
