version: '3.7'

volumes:
  pgdb:

services:
  sentry_redis:
    image: redis
    deploy:
      replicas: 1

  sentry_postgres:
    image: postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: sentry_postgres
      POSTGRES_PASSWORD: 171322f6-3734-464e-9e58-deb6e9a419e5
      POSTGRES_DB: sentry
    volumes:
      - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    ports:
     - 9000:9000
    env_file:
      - .env

  sentry_cron:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    deploy:
      replicas: 1
    command: "sentry run cron"
    env_file:
      - .env

  sentry_worker:
    image: sentry
    links:
     - sentry_redis
     - sentry_postgres
    command: "sentry run worker"
    deploy:
      replicas: 1
    env_file:
      - .env

networks:
  default:
    name: socshared
    driver: overlay
