version: '3.7'
services:

  postgres-db:
    image: postgres:11
    ports:
      - 5533:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - type: bind
        source: /home/gitlab-runner/docker/volumes/postgres
        target: /var/lib/postgresql/data
    env_file:
      - .env_pg

networks:
  default:
    name: socshared