version: '3.7'

services:
  rabbitmq:
    image: 'rabbitmq:3.7.6-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env_rabbit

networks:
  default:
    name: socshared