version: '3.7'

services:
  sentry_postgres:
    image: postgres
    deploy:
      replicas: 1
    environment:
      - .env_sentry_pg

  sentry:
    image: sentry
    deploy:
      replicas: 1
    ports:
     - 9000:9000
    environment:
      - .env_sentry

  sentry_cron:
    image: sentry
    deploy:
      replicas: 1
    command: "sentry run cron"
    environment:
      - .evn_sentry

  sentry_worker:
    image: sentry
    command: "sentry run worker"
    deploy:
      replicas: 1
    environment:
      - .evn_sentry

networks:
  default:
    name: socshared
