version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    image: openzipkin/zipkin:2
    deploy:
      replicas: 1
    ports:
      - 9411:9411
    environment:
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    secrets:
      - rabbitmq_external_secret

secrets:
  rabbitmq_external_secret:
    external: true

networks:
  default:
    name: socshared