version: '3.7'

volumes:
  pg:

services:
  sentry_redis:
    image: vee97/socshared_sentry_redis
    deploy:
      replicas: 1

  sentry_postgres:
    image: vee97/socshared_sentry_postgres
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: 171322f63734464e9e58deb6e9a419e5
      POSTGRES_DB: sentry
    volumes:
      - pg:/var/lib/postgresql/data

networks:
  default:
    name: socshared