version: '3.7'

services:
  sentry_postgres:
    image: postgres
    deploy:
      replicas: 1
    env_file:
      - .env_sentry_pg

  sentry_redis:
    image: redis
    deploy:
      replicas: 1

  sentry:
    image: sentry:9.1.2
    deploy:
      replicas: 1
    ports:
      - 9000:9000
    env_file:
      - .env_sentry

  sentry_cron:
    image: sentry:9.1.2
    deploy:
      replicas: 1
    command: "sentry run cron"
    env_file:
      - .env_sentry

  sentry_worker:
    image: sentry:9.1.2
    command: "sentry run worker"
    deploy:
      replicas: 1
    env_file:
      - .env_sentry

networks:
  default:
    name: socshared