version: '3.3'
services:

  postgres_db:
    image: postgres:11
    ports:
      - 5533:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env_pg

  sentry_redis:
    image: redis

  sentry:
    image: sentry
    ports:
      - 9000:9000
    env_file:
      - .env_sentry

  sentry_cron:
    image: sentry
    command: "sentry run cron"
    env_file:
      - .env_sentry

  sentry_worker:
    image: sentry
    command: "sentry run worker"
    env_file:
      - .env_sentry
