version: '3.7'
services:

  sentry-postgres:
    image: postgres
    env_file:
      - .env_sentry_pg

  sentry-redis:
    image: redis

  sentry:
    container_name: socshared_sentry
    image: sentry
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry upgrade --noinput & sentry createuser --email admin@local.ru --password Admin12345 --superuser --no-input"
    ports:
      - 9000:9000
    env_file:
      - .env_sentry

  sentry-cron:
    image: sentry
    command: "sentry run cron"
    links:
      - sentry-redis
      - sentry-postgres
    env_file:
      - .env_sentry

  sentry-worker:
    image: sentry
    command: "sentry run worker"
    links:
      - sentry-redis
      - sentry-postgres
    env_file:
      - .env_sentry

networks:
  default:
    name: socshared