version: '3.3'
services:

  sentry-postgres:
    image: postgres
    env_file:
      - .env_sentry_pg
    networks:
      - sentry

  sentry-redis:
    image: redis
    networks:
      - sentry

  sentry:
    container_name: socshared_sentry
    image: sentry
    links:
      - sentry-redis
      - sentry-postgres
    ports:
      - 9000:9000
    env_file:
      - .env_sentry
    networks:
      - sentry

  sentry-cron:
    image: sentry
    command: "sentry run cron"
    links:
      - sentry-redis
      - sentry-postgres
    env_file:
      - .env_sentry
    networks:
      - sentry

  sentry-worker:
    image: sentry
    command: "sentry run worker"
    links:
      - sentry-redis
      - sentry-postgres
    env_file:
      - .env_sentry
    networks:
      - sentry
